---

- name: Recursively set permissions and ownership
  ansible.builtin.file:
    path: "{{minio_mount_point}}"
    state: directory
    mode: '0777'
    owner: nobody
    group: nogroup
    recurse: yes

- name: Configure nfs server
  copy:
    dest: /etc/exports
    content: |
      {{minio_mount_point}} *(rw,sync,no_subtree_check,no_root_squash,no_all_squash,fsid=0)
      
- name: Configure nfs server
  ansible.builtin.shell:
    cmd: exportfs -ra

- name: Starting nfs server
  service:
    name: nfs-server 
    state: started
    enabled: yes
