---
- name: Clone GitHub repository
  git:
    repo: "https://github.com/KianBankeLarsen/CTF-Platform"
    dest: "~/CTF-Platform"
    update: yes

- name: install npm packages
  shell: |
    source ~/.nvm/nvm.sh
    npm install
  args:
    chdir: "~/CTF-Platform/src"
    executable: /bin/bash

- name: Deploy stacks
  vars:
    pulumi_passphrase: "{{ lookup('file', '../pulumi_passphrase') }}"
  block:
    - name: Source environment and deploy Pulumi stacks
      shell: |
        source ~/.bashrc
        pulumi stack select ucloud --create
        pulumi up -y
      args:
        chdir: "{{ item }}"
        executable: /bin/bash
      environment:
        PULUMI_CONFIG_PASSPHRASE: "{{ pulumi_passphrase }}"
      loop:
        - "~/CTF-Platform/src/infrastructure"
        - "~/CTF-Platform/src/certificates"
        - "~/CTF-Platform/src/monitoring"
        - "~/CTF-Platform/src/authentication"
        - "~/CTF-Platform/src/application"
