---
- name: Clone GitHub repository
  become_user: "{{ ansible_user }}"
  git:
    repo: "https://github.com/KianBankeLarsen/CTF-Platform"
    dest: "~/CTF-Platform"
    update: yes

- name: install npm packages
  become_user: "{{ ansible_user }}"
  shell: |
    source ~/.nvm/nvm.sh
    npm install
  args:
    chdir: "~/CTF-Platform/src"
    executable: /bin/bash

- name: Pulumi login local
  become_user: "{{ ansible_user }}"
  shell: |
    export PATH=$PATH:$HOME/.pulumi/bin
    pulumi login --local
  args:
    chdir: "~/CTF-Platform/src"
    executable: /bin/bash

- name: Deploy stacks
  become_user: "{{ ansible_user }}"
  vars:
    pulumi_passphrase: "{{ lookup('file', '../pulumi_passphrase') }}"
  block:
    - name: Source environment and deploy Pulumi stacks
      shell: |
        source ~/.nvm/nvm.sh
        export PATH=$PATH:$HOME/.pulumi/bin
        pulumi stack select ucloud --create
        pulumi up -y
      args:
        chdir: "{{ item }}"
        executable: /bin/bash
      environment:
        PULUMI_CONFIG_PASSPHRASE: "{{ pulumi_passphrase }}"
      loop:
        - "~/CTF-Platform/src/infrastructure"
        - "~/CTF-Platform/src/certificates"
        - "~/CTF-Platform/src/monitoring"
        - "~/CTF-Platform/src/authentication"
        - "~/CTF-Platform/src/application"

- name: Restart Step CA
  become_user: "{{ ansible_user }}"
  shell: |
    kubectl rollout restart -n ucloud statefulset step-step-certificates