- name: Clone GitHub repository
  tasks:
    - name: Clone the GitHub repository
      git:
        repo: 'https://github.com/KianBankeLarsen/CTF-Platform'
        dest: '~/CTF-Platform'
        update: yes

- name: Install Node modules
  tasks:
    - name: Install Node modules
      npm:
        path: '~/CTF-Platform/src'
        state: present

- name: Deploy stacks
  vars:
    pulumi_passphrase: "{{ lookup('file', '../pulumi_passphrase') }}"
  tasks:
    - name: Select and deploy stacks
      command: pulumi stack select ucloud --create && pulumi up --stack ucloud -y
      args:
        chdir: "{{ item }}"
      environment:
        PULUMI_CONFIG_PASSPHRASE: "{{ pulumi_passphrase }}"
      loop:
        - '~/CTF-Platform/src/infrastructure'
        - '~/CTF-Platform/src/certificates'
        - '~/CTF-Platform/src/monitoring'
        - '~/CTF-Platform/src/authentication'
        - '~/CTF-Platform/src/application'
