- hosts: k8s-cluster
  gather_facts: true
  become: true
  roles:
    - docker
    - cri-dockerd
    - upgrade

- hosts: control_plane
  gather_facts: true
  become: true
  roles:
    - kubernetes/control
    - ctf-deps
    - pulumi-deploy

- hosts: workers
  gather_facts: true
  become: true
  roles:
    - kubernetes/worker
