- hosts: k8s-cluster
  gather_facts: true
  become: true
  roles:
    - docker
    - cri-dockerd

- hosts: control_plane
  gather_facts: true
  become: true
  roles:
    - { role: kubernetes/control, tags: control }

- hosts: workers
  gather_facts: true
  become: true
  roles:
    - { role: kubernetes/worker, tags: worker }
