- hosts: k8s-cluster
  gather_facts: true
  become: true
  roles:
    - commons/upgrade
    # - commons/minIO
    - docker
    - cri-dockerd

- hosts: control_plane
  gather_facts: true
  become: true
  roles:
    - kubernetes/control

- hosts: workers
  gather_facts: true
  become: true
  roles:
    - commons/minIO
    - kubernetes/worker

- hosts: control_plane
  gather_facts: true
  become: true
  roles:
    - pulumi-deploy
