- hosts: control_plane
  gather_facts: true
  become: true
  roles:
    - kubernetes/reset
    - kubernetes/control

- hosts: workers
  gather_facts: true
  become: true
  roles:
    - kubernetes/reset
    - kubernetes/worker
